# .github/workflows/build-jollyclick.yml
name: Build Jollyclick (C)

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: self-hosted  # ton runner Kubernetes auto-hébergé

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build essentials
        run: |
          sudo apt-get update && \
          sudo apt-get install -y build-essential swi-prolog

      - name: Build Jollyclick
        working-directory: ./jollyclick/src/C
        run: |
          make clean || true
          make

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: jollyclick-bin
          path: ./jollyclick/src/jollyclick
